# Generated by Django 5.2.17 on 2026-09-03 16:45

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado')], default='RASCUNHO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-referencia',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('finalizado_em__isnull', True), ('status', 'RASCUNHO')), models.Q(('finalizado_em__isnull', False), ('status', 'FINALIZADO')), _connector='OR'), name='fechamento_status_data_coerentes')],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('unidade', models.CharField(choices=[('KG', 'Kg'), ('L', 'Litros'), ('UN', 'Unidades')], max_length=2)),
                ('meta_atual', models.DecimalField(decimal_places=3, max_digits=12)),
                ('estoque_atual', models.DecimalField(decimal_places=3, max_digits=12)),
                ('data_validade', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('nome',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='ingrediente_nome_ci_unico'), models.CheckConstraint(condition=models.Q(('meta_atual__gt', 0)), name='ingrediente_meta_positiva'), models.CheckConstraint(condition=models.Q(('estoque_atual__gte', 0)), name='ingrediente_estoque_nao_negativo')],
            },
        ),
        migrations.CreateModel(
            name='ItemFechamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_registrado', models.CharField(max_length=120)),
                ('unidade_registrada', models.CharField(choices=[('KG', 'Kg'), ('L', 'Litros'), ('UN', 'Unidades')], max_length=2)),
                ('meta_anterior', models.DecimalField(decimal_places=3, max_digits=12)),
                ('consumo_mensal', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('estoque_restante', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('validade_registrada', models.DateField(blank=True, null=True)),
                ('houve_falta', models.BooleanField(default=False)),
                ('estava_vencido', models.BooleanField(blank=True, null=True)),
                ('estoque_aproveitavel', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('meta_resultante', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('quantidade_compra', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.fechamentomensal')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_fechamento', to='estoque.ingrediente')),
            ],
            options={
                'ordering': ('nome_registrado',),
                'constraints': [models.UniqueConstraint(fields=('fechamento', 'ingrediente'), name='item_unico_por_fechamento'), models.CheckConstraint(condition=models.Q(('consumo_mensal__isnull', True), ('consumo_mensal__gte', 0), _connector='OR'), name='item_consumo_nao_negativo'), models.CheckConstraint(condition=models.Q(('estoque_restante__isnull', True), ('estoque_restante__gte', 0), _connector='OR'), name='item_estoque_nao_negativo'), models.CheckConstraint(condition=models.Q(('quantidade_compra__isnull', True), ('quantidade_compra__gte', 0), _connector='OR'), name='item_compra_nao_negativa'), models.CheckConstraint(condition=models.Q(('houve_falta', False), ('estoque_restante', 0), _connector='OR'), name='item_falta_exige_estoque_zero')],
            },
        ),
    ]
