# Generated by Django 5.2.17 on 2026-09-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fechamentomensal',
            name='fechamento_status_data_coerentes',
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='referencia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='fechamentomensal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELADO'), _negated=True), fields=('referencia',), name='fechamento_referencia_ativa_unica'),
        ),
        migrations.AddConstraint(
            model_name='fechamentomensal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelado_em__isnull', True), ('finalizado_em__isnull', True), ('status', 'RASCUNHO')), models.Q(('cancelado_em__isnull', True), ('finalizado_em__isnull', False), ('status', 'FINALIZADO')), models.Q(('cancelado_em__isnull', False), ('finalizado_em__isnull', True), ('status', 'CANCELADO')), _connector='OR'), name='fechamento_status_data_coerentes'),
        ),
    ]
